DROP SEQUENCE task_id_seq;
DROP SEQUENCE team_id_seq;
DROP SEQUENCE user_id_seq;
DROP SEQUENCE event_id_seq;


CREATE SEQUENCE task_id_seq START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE team_id_seq START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE user_id_seq START WITH 1
INCREMENT BY 1;
CREATE SEQUENCE event_id_seq START WITH 1
INCREMENT BY 1;

